// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificationTupeMoc.proto

#include "NotificationTupeMoc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr NotificationTupeMoc::NotificationTupeMoc(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : typenotification_(0u){}
struct NotificationTupeMocDefaultTypeInternal {
  constexpr NotificationTupeMocDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NotificationTupeMocDefaultTypeInternal() {}
  union {
    NotificationTupeMoc _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NotificationTupeMocDefaultTypeInternal _NotificationTupeMoc_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_NotificationTupeMoc_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_NotificationTupeMoc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_NotificationTupeMoc_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_NotificationTupeMoc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NotificationTupeMoc, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NotificationTupeMoc, typenotification_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::NotificationTupeMoc)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_NotificationTupeMoc_default_instance_),
};

const char descriptor_table_protodef_NotificationTupeMoc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031NotificationTupeMoc.proto\"/\n\023Notificat"
  "ionTupeMoc\022\030\n\020typeNotification\030\001 \001(\rb\006pr"
  "oto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_NotificationTupeMoc_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NotificationTupeMoc_2eproto = {
  false, false, 84, descriptor_table_protodef_NotificationTupeMoc_2eproto, "NotificationTupeMoc.proto", 
  &descriptor_table_NotificationTupeMoc_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_NotificationTupeMoc_2eproto::offsets,
  file_level_metadata_NotificationTupeMoc_2eproto, file_level_enum_descriptors_NotificationTupeMoc_2eproto, file_level_service_descriptors_NotificationTupeMoc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_NotificationTupeMoc_2eproto_getter() {
  return &descriptor_table_NotificationTupeMoc_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_NotificationTupeMoc_2eproto(&descriptor_table_NotificationTupeMoc_2eproto);

// ===================================================================

class NotificationTupeMoc::_Internal {
 public:
};

NotificationTupeMoc::NotificationTupeMoc(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:NotificationTupeMoc)
}
NotificationTupeMoc::NotificationTupeMoc(const NotificationTupeMoc& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  typenotification_ = from.typenotification_;
  // @@protoc_insertion_point(copy_constructor:NotificationTupeMoc)
}

void NotificationTupeMoc::SharedCtor() {
typenotification_ = 0u;
}

NotificationTupeMoc::~NotificationTupeMoc() {
  // @@protoc_insertion_point(destructor:NotificationTupeMoc)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void NotificationTupeMoc::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void NotificationTupeMoc::ArenaDtor(void* object) {
  NotificationTupeMoc* _this = reinterpret_cast< NotificationTupeMoc* >(object);
  (void)_this;
}
void NotificationTupeMoc::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NotificationTupeMoc::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NotificationTupeMoc::Clear() {
// @@protoc_insertion_point(message_clear_start:NotificationTupeMoc)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  typenotification_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NotificationTupeMoc::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 typeNotification = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          typenotification_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NotificationTupeMoc::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NotificationTupeMoc)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 typeNotification = 1;
  if (this->_internal_typenotification() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_typenotification(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NotificationTupeMoc)
  return target;
}

size_t NotificationTupeMoc::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NotificationTupeMoc)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 typeNotification = 1;
  if (this->_internal_typenotification() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_typenotification());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NotificationTupeMoc::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    NotificationTupeMoc::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NotificationTupeMoc::GetClassData() const { return &_class_data_; }

void NotificationTupeMoc::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<NotificationTupeMoc *>(to)->MergeFrom(
      static_cast<const NotificationTupeMoc &>(from));
}


void NotificationTupeMoc::MergeFrom(const NotificationTupeMoc& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NotificationTupeMoc)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_typenotification() != 0) {
    _internal_set_typenotification(from._internal_typenotification());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NotificationTupeMoc::CopyFrom(const NotificationTupeMoc& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NotificationTupeMoc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NotificationTupeMoc::IsInitialized() const {
  return true;
}

void NotificationTupeMoc::InternalSwap(NotificationTupeMoc* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(typenotification_, other->typenotification_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NotificationTupeMoc::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_NotificationTupeMoc_2eproto_getter, &descriptor_table_NotificationTupeMoc_2eproto_once,
      file_level_metadata_NotificationTupeMoc_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::NotificationTupeMoc* Arena::CreateMaybeMessage< ::NotificationTupeMoc >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NotificationTupeMoc >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
