# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cServer.proto\"\x98\x02\n\x17ServerLogInNotification\x12\x18\n\x10typeNotification\x18\x01 \x01(\r\x12\x11\n\tuserLogin\x18\x02 \x01(\t\x12\x10\n\x08userPass\x18\x03 \x01(\t\x12\x10\n\x08sesionId\x18\x04 \x01(\x04\x12\x0e\n\x06userId\x18\x05 \x01(\x04\x12\x37\n\x07respose\x18\x06 \x01(\x0e\x32!.ServerLogInNotification.ResponseH\x00\x88\x01\x01\"W\n\x08Response\x12\x1e\n\x1a\x41UTHORIZATION_IS_SUCCESFUL\x10\x00\x12\x17\n\x13\x41UTHORIZATION_FAILD\x10\x01\x12\x12\n\x0eUSER_NOT_FOUND\x10\x02\x42\n\n\x08_respose\"\xe6\x01\n\x1eServerRegistrationNotification\x12\x18\n\x10typeNotification\x18\x01 \x01(\r\x12\x0e\n\x06userId\x18\x02 \x01(\x04\x12\x10\n\x08sesionId\x18\x03 \x01(\x04\x12?\n\x08response\x18\x04 \x01(\x0e\x32(.ServerRegistrationNotification.ResponseH\x00\x88\x01\x01\":\n\x08Response\x12\x1d\n\x19REGISTRATION_IS_SUCCESFUL\x10\x00\x12\x0f\n\x0bUSER_EXISTS\x10\x01\x42\x0b\n\t_response\"g\n\x19ServerMessageNotification\x12\x18\n\x10typeNotification\x18\x01 \x01(\r\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x10\n\x08senderId\x18\x03 \x01(\x04\x12\x0c\n\x04text\x18\x04 \x01(\t\"H\n\x1aNewUserConnectNotification\x12\x18\n\x10typeNotification\x18\x01 \x01(\r\x12\x10\n\x08userName\x18\x02 \x01(\tb\x06proto3'
)



_SERVERLOGINNOTIFICATION_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='ServerLogInNotification.Response',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTHORIZATION_IS_SUCCESFUL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHORIZATION_FAILD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=198,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_SERVERLOGINNOTIFICATION_RESPONSE)

_SERVERREGISTRATIONNOTIFICATION_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='ServerRegistrationNotification.Response',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGISTRATION_IS_SUCCESFUL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_EXISTS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=459,
  serialized_end=517,
)
_sym_db.RegisterEnumDescriptor(_SERVERREGISTRATIONNOTIFICATION_RESPONSE)


_SERVERLOGINNOTIFICATION = _descriptor.Descriptor(
  name='ServerLogInNotification',
  full_name='ServerLogInNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeNotification', full_name='ServerLogInNotification.typeNotification', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userLogin', full_name='ServerLogInNotification.userLogin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userPass', full_name='ServerLogInNotification.userPass', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sesionId', full_name='ServerLogInNotification.sesionId', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='ServerLogInNotification.userId', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='respose', full_name='ServerLogInNotification.respose', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERLOGINNOTIFICATION_RESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_respose', full_name='ServerLogInNotification._respose',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=17,
  serialized_end=297,
)


_SERVERREGISTRATIONNOTIFICATION = _descriptor.Descriptor(
  name='ServerRegistrationNotification',
  full_name='ServerRegistrationNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeNotification', full_name='ServerRegistrationNotification.typeNotification', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='ServerRegistrationNotification.userId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sesionId', full_name='ServerRegistrationNotification.sesionId', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='ServerRegistrationNotification.response', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERREGISTRATIONNOTIFICATION_RESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_response', full_name='ServerRegistrationNotification._response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=300,
  serialized_end=530,
)


_SERVERMESSAGENOTIFICATION = _descriptor.Descriptor(
  name='ServerMessageNotification',
  full_name='ServerMessageNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeNotification', full_name='ServerMessageNotification.typeNotification', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userName', full_name='ServerMessageNotification.userName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='senderId', full_name='ServerMessageNotification.senderId', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='ServerMessageNotification.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=635,
)


_NEWUSERCONNECTNOTIFICATION = _descriptor.Descriptor(
  name='NewUserConnectNotification',
  full_name='NewUserConnectNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeNotification', full_name='NewUserConnectNotification.typeNotification', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userName', full_name='NewUserConnectNotification.userName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=709,
)

_SERVERLOGINNOTIFICATION.fields_by_name['respose'].enum_type = _SERVERLOGINNOTIFICATION_RESPONSE
_SERVERLOGINNOTIFICATION_RESPONSE.containing_type = _SERVERLOGINNOTIFICATION
_SERVERLOGINNOTIFICATION.oneofs_by_name['_respose'].fields.append(
  _SERVERLOGINNOTIFICATION.fields_by_name['respose'])
_SERVERLOGINNOTIFICATION.fields_by_name['respose'].containing_oneof = _SERVERLOGINNOTIFICATION.oneofs_by_name['_respose']
_SERVERREGISTRATIONNOTIFICATION.fields_by_name['response'].enum_type = _SERVERREGISTRATIONNOTIFICATION_RESPONSE
_SERVERREGISTRATIONNOTIFICATION_RESPONSE.containing_type = _SERVERREGISTRATIONNOTIFICATION
_SERVERREGISTRATIONNOTIFICATION.oneofs_by_name['_response'].fields.append(
  _SERVERREGISTRATIONNOTIFICATION.fields_by_name['response'])
_SERVERREGISTRATIONNOTIFICATION.fields_by_name['response'].containing_oneof = _SERVERREGISTRATIONNOTIFICATION.oneofs_by_name['_response']
DESCRIPTOR.message_types_by_name['ServerLogInNotification'] = _SERVERLOGINNOTIFICATION
DESCRIPTOR.message_types_by_name['ServerRegistrationNotification'] = _SERVERREGISTRATIONNOTIFICATION
DESCRIPTOR.message_types_by_name['ServerMessageNotification'] = _SERVERMESSAGENOTIFICATION
DESCRIPTOR.message_types_by_name['NewUserConnectNotification'] = _NEWUSERCONNECTNOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerLogInNotification = _reflection.GeneratedProtocolMessageType('ServerLogInNotification', (_message.Message,), {
  'DESCRIPTOR' : _SERVERLOGINNOTIFICATION,
  '__module__' : 'Server_pb2'
  # @@protoc_insertion_point(class_scope:ServerLogInNotification)
  })
_sym_db.RegisterMessage(ServerLogInNotification)

ServerRegistrationNotification = _reflection.GeneratedProtocolMessageType('ServerRegistrationNotification', (_message.Message,), {
  'DESCRIPTOR' : _SERVERREGISTRATIONNOTIFICATION,
  '__module__' : 'Server_pb2'
  # @@protoc_insertion_point(class_scope:ServerRegistrationNotification)
  })
_sym_db.RegisterMessage(ServerRegistrationNotification)

ServerMessageNotification = _reflection.GeneratedProtocolMessageType('ServerMessageNotification', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGENOTIFICATION,
  '__module__' : 'Server_pb2'
  # @@protoc_insertion_point(class_scope:ServerMessageNotification)
  })
_sym_db.RegisterMessage(ServerMessageNotification)

NewUserConnectNotification = _reflection.GeneratedProtocolMessageType('NewUserConnectNotification', (_message.Message,), {
  'DESCRIPTOR' : _NEWUSERCONNECTNOTIFICATION,
  '__module__' : 'Server_pb2'
  # @@protoc_insertion_point(class_scope:NewUserConnectNotification)
  })
_sym_db.RegisterMessage(NewUserConnectNotification)


# @@protoc_insertion_point(module_scope)
