# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Server
DESTDIR = ./x64/Debug
CONFIG += debug console
LIBS += -L"../../../../../../../../install/lib" \
    -L"../../../../../../../../protobuf-3.17.3/Debug" \
    -llibprotobuf
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(Server.pri)
