# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Server
DESTDIR = ./x64/Debug
CONFIG += debug console
QT += network
LIBS += -lprotobuf
DEPENDPATH += .
MOC_DIR += .
UI_DIR += .
RCC_DIR += .
include(Server.pri)

SUBDIRS += \
    ../Client/Client.pro
